apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - frontend.yaml
  - redis.yaml
  - ingress.yaml

commonLabels:
  project: unilm

images:
  - name: unilmprod.azurecr.io/backend
    newTag: latest
  - name: unilmprod.azurecr.io/frontend
    newTag: latest