apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- redis.yaml
- ingress.yaml

commonLabels:
  project: unilm

images:
- name: unilmprod.azurecr.io/backend
  newTag: 9a5936a701ec4c6c4f2fd7128678ce7bdd12c1a6
- name: unilmprod.azurecr.io/frontend
  newTag: 9a5936a701ec4c6c4f2fd7128678ce7bdd12c1a6
