apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- redis.yaml
- ingress.yaml

commonLabels:
  project: unilm

images:
- name: unilmprod.azurecr.io/backend
  newTag: 3c0004ab356e0952cdeb5a1c6622c4ebedf3c7b3
- name: unilmprod.azurecr.io/frontend
  newTag: 3c0004ab356e0952cdeb5a1c6622c4ebedf3c7b3
